03 - Models/publicationdb/config/routes.rb
Publicationdb::Application.routes.draw do
  resources :authors

  resources :papers

end

03 - Models/publicationdb/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :publication
  has_many :papers, :through => :publication
  
  attr_accessible :name, :email, :gender, :male

  validates :name,  :presence => true, 
                      :length => {:minimum => 1, :maximum => 254}
  
  validates :email, :presence => true, 
                      :length => {:minimum => 3, :maximum => 254},
                      :uniqueness => true,
                      :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  
  attr_accessor :gender
  validates :gender, :inclusion => {:in => %w{male female}, :message => "is not male or female"}
  before_save :set_male_or_female

  protected

  def set_male_or_female
    self.male = (@gender == "male")
  end

end

03 - Models/publicationdb/app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :title, :abstract, :submitted, :accepted, :rejected
  has_many :publication
  has_many :authors, :through => :publication
end

03 - Models/publicationdb/app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :paper
  
  validates_uniqueness_of :author_id, :scope => :paper_id
end

03 - Models/publicationdb/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.xml
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.xml
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, :notice => 'Author was successfully created.') }
        format.xml  { render :xml => @author, :status => :created, :location => @author }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to(@author, :notice => 'Author was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to(authors_url) }
      format.xml  { head :ok }
    end
  end
end

03 - Models/publicationdb/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.xml
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.xml
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.xml
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.xml
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to(@paper, :notice => 'Paper was successfully created.') }
        format.xml  { render :xml => @paper, :status => :created, :location => @paper }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.xml
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to(@paper, :notice => 'Paper was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.xml
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to(papers_url) }
      format.xml  { head :ok }
    end
  end
end

03 - Models/publicationdb/app/helpers/papers_helper.rb
module PapersHelper
end

03 - Models/publicationdb/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

03 - Models/publicationdb/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

03 - Models/publicationdb/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.email %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

03 - Models/publicationdb/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

03 - Models/publicationdb/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

03 - Models/publicationdb/app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :submitted %><br />
    <%= f.date_select :submitted %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.date_select :accepted %>
  </div>
  <div class="field">
    <%= f.label :rejected %><br />
    <%= f.check_box :rejected %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

03 - Models/publicationdb/app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

03 - Models/publicationdb/app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Abstract</th>
    <th>Submitted</th>
    <th>Accepted</th>
    <th>Rejected</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.title %></td>
    <td><%= paper.abstract %></td>
    <td><%= paper.submitted %></td>
    <td><%= paper.accepted %></td>
    <td><%= paper.rejected %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

03 - Models/publicationdb/app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

03 - Models/publicationdb/app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Abstract:</b>
  <%= @paper.abstract %>
</p>

<p>
  <b>Submitted:</b>
  <%= @paper.submitted %>
</p>

<p>
  <b>Accepted:</b>
  <%= @paper.accepted %>
</p>

<p>
  <b>Rejected:</b>
  <%= @paper.rejected %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>